name: build and test sqr function
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '4.7.x'
          working-directory: archtekt2
      - run: dotnet build archtekt2
      - run: dotnet test archtekt2_test
